#!/usr/bin/env escript
%% -*- Mode: erlang -*-

main(Dirs) ->
    lists:foreach(fun(Dir) -> make(Dir) end, Dirs).

make(Dir) ->
    io:format("~n\033[32mEmaking ~s\033[0m~n", [Dir]),
    {ok, CurDir} = file:get_cwd(),
    ok = file:set_cwd(Dir),
    case make:all([debug_info, {i, "../include"}, {outdir, "../ebin"}]) of
        error -> halt(1);
        _ -> file:set_cwd(CurDir)
    end.
