#!/usr/bin/env escript
%% -*- Mode: erlang -*-

main(Dirs) ->
    lists:foreach(fun(Dir) -> make(Dir) end, Dirs).

make(Dir) ->
    io:format("~n\033[32mEmaking ~s~s\033[0m~n", [strict_string(), Dir]),
    {ok, CurDir} = file:get_cwd(),
    ok = file:set_cwd(Dir),
    case make:all(get_options()) of
        error -> halt(1);
        _ -> file:set_cwd(CurDir)
    end.

strict() -> "true" =:= os:getenv("EMAKE_STRICT").

get_options() ->
    Strict =
        case strict() of
            true ->
                [warnings_as_errors];
            false ->
                []
        end,
    [debug_info, {i, "../include"}, {outdir, "../ebin"} | Strict].

strict_string() ->
    case strict() of
        true -> "(strict) ";
        false -> ""
    end.
